name: voidtask
version: 1.0.0+1
publish_to: none
description: Minimalist void tracker - task manager
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  appwrite: ^11.0.1

  handy_window: ^0.3.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_tabler_icons: ^1.9.0
  flutter_easyloading: ^3.0.5
  flutter_animate: ^4.3.0
  simple_gradient_text: ^1.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

