name: nanoplan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_tabler_icons: ^1.9.0
  google_fonts: ^6.1.0
  handy_window: ^0.3.1
  keymap: ^0.0.92
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  get: ^4.6.6
  flutter: 
    sdk: flutter
  nanoid: ^1.0.0

dev_dependencies: 
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

