name: nanoplan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  appwrite: ^11.0.1
  flutter_side_menu: ^0.4.0
  flutter_tabler_icons: ^1.9.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  handy_window: ^0.3.1
  get: ^4.6.6

  flutter: 
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

